apiVersion: v1
kind: Service
metadata:
  labels:
    app: archiver
    component: archiver-api
    env: nonprod
  name: archiver-api-nonprod-rust-http
  namespace: archiver
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    app: archiver
    component: archiver-api
    env: nonprod
  type: NodePort
