apiVersion: v1
kind: Service
metadata:
  labels:
    app: archiver
    component: archiver-api
    env: nonprod
  name: archiver-api-nonprod-rust-http
  namespace: archiver
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: archiver
    component: archiver-api
    env: nonprod
  type: NodePort
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: archiver
  namespace: ambassador
spec:
  prefix: /
  service: archiver-api-nonprod-rust-http.archiver:8000
