apiVersion: v1
kind: Service
metadata:
  labels:
    app: rust
    component: archiver-api
    env: nonprod
  name: archiver-apinonprod-rust-http
  namespace: archiver
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: rust
    component: archiver-api
    env: nonprod
  type: ClusterIP
