apiVersion: v1
kind: Service
metadata:
  labels:
    app: archiver
    component: database
    env: nonprod
  name: postgres
  namespace: archiver
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: archiver
    component: database
    env: nonprod
  type: ClusterIP
