apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: archiver
    component: database
    env: nonprod
  name: postgres
  namespace: archiver
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: archiver
      component: database
      env: nonprod
  template:
    metadata:
      labels:
        app: archiver
        component: database
        env: nonprod
    spec:
      containers:
      - args: []
        command: []
        env:
        - name: POSTGRES_USER
          value: something
        - name: POSTGRES_PASSWORD
          value: somethingelse
        - name: POSTGRES_DB
          value: archiver
        image: postgres:11.5-alpine
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        volumeMounts: []
      initContainers: []
      serviceAccountName: default
