---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: ambassador
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 80
      name: http
      targetPort: 8080
    - port: 443
      name: https
      targetPort: 8443
  selector:
    service: ambassador
