apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: archiver.nhyne.dev
  labels:
    app: rust
    component: archiver-api
    env: prod
  name: archiver-apiprod-rust-http
  namespace: archiver
spec:
  ports:
  - port: 443
    targetPort: 8000
  selector:
    app: rust
    component: archiver-api
    env: prod
  type: LoadBalancer
