apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: archiver
    component: archiver-api
    env: prod
  name: archiver-api
  namespace: archiver
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: archiver
      component: archiver-api
      env: prod
  template:
    metadata:
      labels:
        app: archiver
        component: archiver-api
        env: prod
    spec:
      containers:
      - args: []
        command: []
        env:
        - name: DATABASE_URL
          value: postgres://something:somethingelse@postgres:5432/archiver
        image: nhyne/archiver-api:0.0.1-alpha
        name: rust
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        volumeMounts: []
      initContainers: []
      serviceAccountName: default
