apiVersion: v1
kind: Service
metadata:
  labels:
    app: rust
    component: archiver-api
    env: prod
  name: archiver-api-archiver-api-something
  namespace: archiver
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: rust
    component: archiver-api
    env: prod
type: ClusterIp
