apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: user.nhyne.dev
  labels:
    app: user
    component: user-api
    env: prod
  name: user-api-prod-rust-http
  namespace: user
spec:
  ports:
  - port: 80
    targetPort: 8001
  selector:
    app: user
    component: user-api
    env: prod
  type: LoadBalancer
