apiVersion: v1
kind: ConfigMap
metadata:
  name: dsl-job-config
  namespace: jenkins
data:
  config.xml: |
    <?xml version='1.1' encoding='UTF-8'?>
    <project>
        <actions/>
        <description>DSL Job</description>
        <keepDependencies>false</keepDependencies>
        <properties>
            <hudson.model.ParametersDefinitionProperty>
                <parameterDefinitions>
                    <hudson.model.StringParameterDefinition>
                        <name>branch</name>
                        <description>which branch to use</description>
                        <defaultValue>master</defaultValue>
                        <trim>false</trim>
                    </hudson.model.StringParameterDefinition>
                </parameterDefinitions>
            </hudson.model.ParametersDefinitionProperty>
        </properties>
        <scm class="hudson.plugins.git.GitSCM" plugin="git@3.9.3">
            <configVersion>2</configVersion>
            <userRemoteConfigs>
                <hudson.plugins.git.UserRemoteConfig>
                    <url>https://github.com/nhyne/jenkins.git</url>
                </hudson.plugins.git.UserRemoteConfig>
            </userRemoteConfigs>
            <branches>
                <hudson.plugins.git.BranchSpec>
                    <name>master</name>
                </hudson.plugins.git.BranchSpec>
            </branches>
            <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
            <submoduleCfg class="list"/>
            <extensions/>
        </scm>
        <canRoam>true</canRoam>
        <disabled>false</disabled>
        <blockBuildWhenDownstreamBuilding>false</blockBuildWhenDownstreamBuilding>
        <blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>
        <triggers>
            <com.cloudbees.jenkins.GitHubPushTrigger plugin="github@1.29.3">
                <spec></spec>
            </com.cloudbees.jenkins.GitHubPushTrigger>
            <hudson.triggers.SCMTrigger>
                <spec>H/2 * * * *</spec>
                <ignorePostCommitHooks>false</ignorePostCommitHooks>
            </hudson.triggers.SCMTrigger>
        </triggers>
        <concurrentBuild>false</concurrentBuild>
        <builders>
            <javaposse.jobdsl.plugin.ExecuteDslScripts plugin="job-dsl@1.72">
                <targets>jobs/*.groovy</targets>
                <usingScriptText>false</usingScriptText>
                <sandbox>false</sandbox>
                <ignoreExisting>false</ignoreExisting>
                <ignoreMissingFiles>false</ignoreMissingFiles>
                <failOnMissingPlugin>true</failOnMissingPlugin>
                <unstableOnDeprecation>false</unstableOnDeprecation>
                <removedJobAction>DELETE</removedJobAction>
                <removedViewAction>DELETE</removedViewAction>
                <removedConfigFilesAction>DELETE</removedConfigFilesAction>
                <lookupStrategy>JENKINS_ROOT</lookupStrategy>
                <additionalClasspath>src/main/groovy</additionalClasspath>
            </javaposse.jobdsl.plugin.ExecuteDslScripts>
        </builders>
        <publishers/>
        <buildWrappers>
            <hudson.plugins.ws__cleanup.PreBuildCleanup plugin="ws-cleanup@0.37">
                <deleteDirs>false</deleteDirs>
                <cleanupParameter></cleanupParameter>
                <externalDelete></externalDelete>
                <disableDeferredWipeout>false</disableDeferredWipeout>
            </hudson.plugins.ws__cleanup.PreBuildCleanup>
        </buildWrappers>
    </project>
  dsl-security.xml: |
    <?xml version='1.1' encoding='UTF-8'?>
    <javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration plugin="job-dsl@1.72">
      <category class="jenkins.model.GlobalConfigurationCategory$Security"/>
      <useScriptSecurity>false</useScriptSecurity>
    </javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration>
