---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: archiver
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: git-sync
          image: nhyne/git-sync:1.0.0__linux_amd64
          command: ["/git-sync"]
          args: ["--repo=https://github.com/nhyne/archiver-api", "--branch=develop", "--one-time"]
          volumeMounts:
            - mountPath: /tmp/git
              name: git
        # need to clone the api repo to a directory
        - name: ls
          image: alpine:latest
          command: ["ls"]
          args: ["-la", "/home/archiver-api"]
          volumeMounts:
            - mountPath: /home
              name: git
        # need to run diesel setup to execute the migrations and init the DB
      containers:
      - name: postgres
        image: postgres:11.5-alpine
        env:
          - name: POSTGRES_USER
            value: something
          - name: POSTGRES_PASSWORD
            value: somethingelse
          - name: POSTGRES_DB
            value: archiver
        ports:
        - containerPort: 5432
          protocol: TCP
      volumes:
        - name: git
          emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: archiver
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
