---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: archiver
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:11.5-alpine
        env:
          - name: POSTGRES_USER
            value: something
          - name: POSTGRES_PASSWORD
            value: somethingelse
          - name: POSTGRES_DB
            value: archiver
        ports:
        - containerPort: 5432
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: archiver
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
