apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
    component: database
    env: nonprod
  name: postgres-user
  namespace: user
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: user
    component: database
    env: nonprod
  type: ClusterIP
