apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
    component: user-api
    env: nonprod
  name: user-api-nonprod-rust-http
  namespace: user
spec:
  ports:
  - port: 80
    targetPort: 8001
  selector:
    app: user
    component: user-api
    env: nonprod
  type: NodePort
