apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
    component: user-api
    env: nonprod
  name: user-api
  namespace: user
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: user
    component: user-api
    env: nonprod
  type: ClusterIP
