---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: archiver_api
  name: archiver_api
  namespace: archiver
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: archiver_api
  template:
    metadata:
      labels:
        app: archiver_api
    spec:
      containers:
      - name: archiver_api
        image: nhyne/archiver_api:0.0.1-alpha
        ports:
        - containerPort: 8000
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: archiver_api
  name: archiver_api
  namespace: archiver
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 8000
  selector:
    app: archiver_api
