---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    component: archiver-api
  name: archiver-api
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: archiver-api
  template:
    metadata:
      labels:
        component: archiver-api
    spec:
      containers:
      - name: archiver-api
        image: nhyne/archiver-api:0.0.1-alpha
        env:
          - name: DATABASE_URL
            value: postgres://something:somethingelse@postgres:5432/archiver
        ports:
          - containerPort: 8000
            protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  labels:
    component: archiver-api
  name: archiver-api
  namespace: archiver
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 8000
