---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: archiver-api
  namespace: ambassador
spec:
  prefix: /
  service: archiver-api.archiver
  host: archiver.nhyne.localhost
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: user-api
  namespace: ambassador
spec:
  prefix: /
  service: user-api.user
  host: user.nhyne.localhost
