apiVersion: v1
kind: Service
metadata:
  labels:
    app: archiver
    component: archiver-api
    env: prod
  name: archiver-api
  namespace: archiver
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: archiver
    component: archiver-api
    env: prod
  type: ClusterIP
