apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: archiver.nhyne.dev
  labels:
    app: archiver
    component: archiver-api
    env: prod
  name: archiver-api-prod-rust-http
  namespace: archiver
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: archiver
    component: archiver-api
    env: prod
  type: LoadBalancer
