apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: archiver
    component: database-init
    env: prod
  name: diesel-init
  namespace: archiver
spec:
  template:
    metadata:
      labels:
        app: archiver
        component: database-init
        env: prod
    spec:
      containers:
      - args:
        - migration
        - run
        command:
        - diesel
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: database_url
              name: archiver
        image: nhyne/diesel-cli:postgres-11.4
        name: diesel
        ports: []
        volumeMounts:
        - mountPath: /home
          name: git
          readOnly: false
        workingDir: /home/archiver-api/
      initContainers:
      - args:
        - --repo=https://github.com/nhyne/archiver-api
        - --branch=master
        - --one-time
        command:
        - /git-sync
        env: []
        image: nhyne/git-sync:1.0.0__linux_amd64
        name: git-sync
        ports: []
        volumeMounts:
        - mountPath: /tmp/git
          name: git
          readOnly: false
      restartPolicy: Never
      serviceAccountName: default
      volumes:
      - emptyDir: {}
        name: git
