kind: v1
metadata:
  labels:
    name: drone
  name: drone
type: Namespace
---
kind: v1
metadata:
  labels:
    name: archiver
  name: archiver
type: Namespace
---
kind: v1
metadata:
  labels:
    name: utility
  name: utility
type: Namespace
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rust
    component: archiver-api
    env: prod
  name: archiver-api-archiver-api-something
  namespace: archiver
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: rust
    component: archiver-api
    env: prod
type: ClusterIp
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: drone.nhyne.dev
  labels:
    app: drone-server
    component: drone
    env: prod
  name: drone-server-https-port
  namespace: drone
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: drone-server
    component: drone
    env: prod
type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rust
    component: archiver-api
    env: prod
  name: archiver-api
  namespace: archiver
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rust
      component: archiver-api
      env: prod
  template:
    metadata:
      labels:
        app: rust
        component: archiver-api
        env: prod
    spec:
      containers:
      - args: []
        env:
        - name: DATABASE_URL
          value: postgres://something:somethingelse@postgres:5432/archiver
        image: nhyne/archiver-api:0.0.1-alpha
        name: archiver-api
        ports:
        - containerPort: 8000
          name: something
          protocol: TCP
      serviceAccountName: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: external-dns
    component: external-dns
    env: prod
  name: external-dns
  namespace: utility
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: external-dns
      component: external-dns
      env: prod
  template:
    metadata:
      labels:
        app: external-dns
        component: external-dns
        env: prod
    spec:
      containers:
      - args:
        - --source=service
        - --source=ingress
        - --domain-filter=nhyne.dev
        - --domain-filter=nhyne.io
        - --domain-filter=adamjohnson.dev
        - --domain-filter=johnsona.dev
        - --provider=google
        - --registry=txt
        - '--txt-owner-id=nhyne-kube-utility '
        env: []
        image: registry.opensource.zalan.do/teapot/external-dns:v0.5.11
        name: external-dns
        ports: []
      serviceAccountName: external-dns
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: drone-server
    component: drone
    env: prod
  name: drone-server
  namespace: drone
serviceName: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-server
      component: drone
      env: prod
  template:
    metadata:
      labels:
        app: drone-server
        component: drone
        env: prod
    spec:
      containers:
      - args: []
        env:
        - name: DRONE_KUBERNETES_ENABLED
          value: "true"
        - name: DRONE_KUBERNETES_NAMESPACE
          value: drone
        - name: DRONE_LOGS_DEBUG
          value: "true"
        - name: DRONE_ADMIN
          value: nhyne
        - name: DRONE_SERVER_HOST
          value: drone.nhyne.dev
        - name: DRONE_GITHUB_CLIENT_ID
          value: a633f44f1ac044185bb3
        - name: DRONE_TLS_AUTOCERT
          value: "true"
        - name: DRONE_GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client_secret
              name: drone
        - name: DRONE_RPC_SECRET
          valueFrom:
            secretKeyRef:
              key: drone_rpc_secret
              name: drone
        image: drone/drone:1.0.0
        name: server
        ports:
        - containerPort: 443
          name: https-port
          protocol: TCP
      serviceAccountName: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: utility

